export type ProgramCategory = 'calistenia' | 'gym' | 'hibrido';
export type ProgramLevel = 'principiante' | 'intermedio' | 'avanzado';
export type ProgramGoal = 'fuerza' | 'hipertrofia' | 'perdida-grasa' | 'habilidades';

export interface Program {
  id: number;
  slug: string;
  nombre: string;
  categoria: ProgramCategory;
  nivel: ProgramLevel;
  duracion: string;
  objetivo: ProgramGoal;
  descripcion: string;
  precio: string;
  destacado: boolean;
  rating: number;
  cantidadVideos: number;
  beneficios: string[];
}

export const programs: Program[] = [
  // ── CALISTENIA ─────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: 'calistenia-fundamentals',
    nombre: 'Calistenia Fundamentals',
    categoria: 'calistenia',
    nivel: 'principiante',
    duracion: '8 semanas',
    objetivo: 'habilidades',
    descripcion: 'Aprende desde cero los movimientos fundamentales del peso corporal. El punto de partida ideal.',
    precio: '$49',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 48,
    beneficios: ['Domina los movimientos básicos', 'Construye fuerza funcional', 'Corrección postural', 'Progresión estructurada'],
  },
  {
    id: 2,
    slug: 'dominadas-pro',
    nombre: 'Dominadas Pro',
    categoria: 'calistenia',
    nivel: 'principiante',
    duracion: '6 semanas',
    objetivo: 'fuerza',
    descripcion: 'Consigue tu primera dominada y progresa hasta series de 15+ repeticiones con técnica perfecta.',
    precio: '$39',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 32,
    beneficios: ['Primera dominada garantizada', 'Técnica perfecta', 'Progresiones graduales', 'Fuerza de tracción real'],
  },
  {
    id: 3,
    slug: 'muscle-up-system',
    nombre: 'Muscle Up System',
    categoria: 'calistenia',
    nivel: 'intermedio',
    duracion: '10 semanas',
    objetivo: 'habilidades',
    descripcion: 'Desde cero hasta muscle up estricto. Un sistema completo de progresión biomecánica.',
    precio: '$59',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 55,
    beneficios: ['Muscle up estricto como objetivo', 'Fuerza de empuje y tracción', 'Técnica de kip y explosión', 'Progresiones por fase'],
  },
  {
    id: 4,
    slug: 'front-lever-master',
    nombre: 'Front Lever Master',
    categoria: 'calistenia',
    nivel: 'avanzado',
    duracion: '16 semanas',
    objetivo: 'fuerza',
    descripcion: 'Progresión completa hacia el front lever: desde tucado hasta full lever con control total.',
    precio: '$69',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 60,
    beneficios: ['Progresión completa tuck → full', 'Fuerza isométrica máxima', 'Movilidad de hombros', 'Protocolo de frecuencia óptima'],
  },
  {
    id: 5,
    slug: 'planche-master',
    nombre: 'Planche Master',
    categoria: 'calistenia',
    nivel: 'avanzado',
    duracion: '20 semanas',
    objetivo: 'fuerza',
    descripcion: 'Desde tuck planche hasta full planche. El programa más completo para dominar este elemento de élite.',
    precio: '$79',
    destacado: true,
    rating: 5.0,
    cantidadVideos: 72,
    beneficios: [
      'Full planche como objetivo final',
      'Prehab de muñecas y hombros',
      'Periodización en bloques científica',
      'Protocolo isométrico avanzado',
      'Videos en alta definición',
      'Soporte directo del coach',
    ],
  },
  {
    id: 6,
    slug: 'handstand-academy',
    nombre: 'Handstand Academy',
    categoria: 'calistenia',
    nivel: 'intermedio',
    duracion: '12 semanas',
    objetivo: 'habilidades',
    descripcion: 'Control corporal completo. Aprende el handstand estático y sus transiciones con base científica.',
    precio: '$59',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 50,
    beneficios: ['Handstand de 30 segundos', 'Balance y propiocepción', 'Transiciones fluidas', 'Técnica de caída segura'],
  },
  {
    id: 7,
    slug: 'human-flag',
    nombre: 'Human Flag',
    categoria: 'calistenia',
    nivel: 'avanzado',
    duracion: '14 semanas',
    objetivo: 'habilidades',
    descripcion: 'Progresión completa hacia la bandera humana. Uno de los elementos más espectaculares de la calistenia.',
    precio: '$69',
    destacado: false,
    rating: 4.7,
    cantidadVideos: 44,
    beneficios: ['Progresión hacia bandera completa', 'Fuerza lateral máxima', 'Técnica de apalancamiento', 'Ejercicios asistidos'],
  },
  {
    id: 8,
    slug: 'calisthenics-endurance',
    nombre: 'Calisthenics Endurance',
    categoria: 'calistenia',
    nivel: 'intermedio',
    duracion: '8 semanas',
    objetivo: 'hipertrofia',
    descripcion: 'Altas repeticiones, máxima resistencia muscular. Desarrolla capacidad aeróbica y fuerza resistente.',
    precio: '$49',
    destacado: false,
    rating: 4.6,
    cantidadVideos: 38,
    beneficios: ['Resistencia muscular extrema', 'Alta densidad de entrenamiento', 'Circuitos cronometrados', 'Progresión de volumen'],
  },

  // ── GYM ────────────────────────────────────────────────────────────────────
  {
    id: 9,
    slug: 'hipertrofia-inteligente',
    nombre: 'Hipertrofia Inteligente',
    categoria: 'gym',
    nivel: 'intermedio',
    duracion: '12 semanas',
    objetivo: 'hipertrofia',
    descripcion: 'Construye músculo con base en evidencia científica. Periodización, volumen óptimo y técnica correcta.',
    precio: '$59',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 65,
    beneficios: ['Máxima hipertrofia', 'Periodización en bloques', 'Técnica corregida en video', 'Tabla de seguimiento'],
  },
  {
    id: 10,
    slug: 'fuerza-maxima',
    nombre: 'Fuerza Máxima',
    categoria: 'gym',
    nivel: 'avanzado',
    duracion: '16 semanas',
    objetivo: 'fuerza',
    descripcion: 'Maximiza tus marcas en sentadilla, press de banca y peso muerto. Periodización avanzada de powerlifting.',
    precio: '$69',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 58,
    beneficios: ['Máximos en los 3 levantamientos', 'Técnica de powerlifter', 'Periodización ondulante', 'Calentamiento y activación'],
  },
  {
    id: 11,
    slug: 'powerbuilding',
    nombre: 'Powerbuilding',
    categoria: 'gym',
    nivel: 'intermedio',
    duracion: '12 semanas',
    objetivo: 'fuerza',
    descripcion: 'Lo mejor de fuerza e hipertrofia combinados. Gana fuerza y músculo al mismo tiempo.',
    precio: '$59',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 52,
    beneficios: ['Fuerza e hipertrofia simultánea', 'Compuestos + aislamientos', 'Protocolo de deload', 'Seguimiento semana a semana'],
  },
  {
    id: 12,
    slug: 'perdida-de-grasa',
    nombre: 'Pérdida de Grasa',
    categoria: 'gym',
    nivel: 'principiante',
    duracion: '10 semanas',
    objetivo: 'perdida-grasa',
    descripcion: 'Pierde grasa y preserva músculo. Protocolos de entrenamiento y nutrición integrados.',
    precio: '$49',
    destacado: false,
    rating: 4.7,
    cantidadVideos: 42,
    beneficios: ['Déficit calórico guiado', 'Preservación muscular', 'HIIT y LISS combinados', 'Guía nutricional incluida'],
  },
  {
    id: 13,
    slug: 'recomposicion-corporal',
    nombre: 'Recomposición Corporal',
    categoria: 'gym',
    nivel: 'intermedio',
    duracion: '16 semanas',
    objetivo: 'perdida-grasa',
    descripcion: 'Pierde grasa y gana músculo al mismo tiempo. El protocolo más completo para recomponer tu cuerpo.',
    precio: '$69',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 60,
    beneficios: ['Recomposición sin dieta extrema', 'Ciclado calórico inteligente', 'Base de fuerza integrada', 'Seguimiento semanal'],
  },
  {
    id: 14,
    slug: 'principiantes-gym',
    nombre: 'Entrenamiento para Principiantes',
    categoria: 'gym',
    nivel: 'principiante',
    duracion: '8 semanas',
    objetivo: 'hipertrofia',
    descripcion: 'El punto de partida ideal para quien comienza en el gimnasio. Sin complicaciones, sin excusas.',
    precio: '$39',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 36,
    beneficios: ['Base sólida garantizada', 'Movimientos fundamentales', 'Sin equipo especial', 'Guía de nutrición básica'],
  },
  {
    id: 15,
    slug: 'entrenamiento-mujeres',
    nombre: 'Entrenamiento para Mujeres',
    categoria: 'gym',
    nivel: 'principiante',
    duracion: '12 semanas',
    objetivo: 'hipertrofia',
    descripcion: 'Diseñado específicamente para la fisiología femenina. Tonificación, fuerza y confianza real.',
    precio: '$49',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 48,
    beneficios: ['Protocolo para fisiología femenina', 'Glúteos y piernas priorizados', 'Fuerza funcional real', 'Sin miedo a ponerse grande'],
  },
  {
    id: 16,
    slug: 'entrenamiento-funcional',
    nombre: 'Entrenamiento Funcional',
    categoria: 'gym',
    nivel: 'intermedio',
    duracion: '10 semanas',
    objetivo: 'habilidades',
    descripcion: 'Mejora tu rendimiento en actividades cotidianas y deportivas con movimientos funcionales.',
    precio: '$49',
    destacado: false,
    rating: 4.7,
    cantidadVideos: 44,
    beneficios: ['Movimientos funcionales', 'Mejora deportiva real', 'Estabilidad y coordinación', 'Prevención de lesiones'],
  },

  // ── HÍBRIDO ────────────────────────────────────────────────────────────────
  {
    id: 17,
    slug: 'gym-calistenia',
    nombre: 'Gym + Calistenia',
    categoria: 'hibrido',
    nivel: 'intermedio',
    duracion: '12 semanas',
    objetivo: 'fuerza',
    descripcion: 'Lo mejor de ambos mundos. Combina pesas y peso corporal para un físico completo y funcional.',
    precio: '$59',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 56,
    beneficios: ['Fuerza máxima y funcional', 'Habilidades de peso corporal', 'Periodización mixta', 'Adaptable a gym o parque'],
  },
  {
    id: 18,
    slug: 'streetlifting',
    nombre: 'Streetlifting',
    categoria: 'hibrido',
    nivel: 'avanzado',
    duracion: '16 semanas',
    objetivo: 'fuerza',
    descripcion: 'La fusión de powerlifting y calistenia. Peso muerto + dominadas. Sentadilla + muscle up.',
    precio: '$69',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 62,
    beneficios: ['Preparación para competición', 'Peso muerto + dominadas', 'Squat + muscle up', 'Pico de forma competitivo'],
  },
  {
    id: 19,
    slug: 'power-calisthenics',
    nombre: 'Power Calisthenics',
    categoria: 'hibrido',
    nivel: 'avanzado',
    duracion: '14 semanas',
    objetivo: 'fuerza',
    descripcion: 'Máxima producción de fuerza con tu propio peso. Elementos estáticos y dinámicos de élite.',
    precio: '$69',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 58,
    beneficios: ['Fuerza explosiva máxima', 'Elementos avanzados combinados', 'Pliometría de alto nivel', 'Combinaciones complejas'],
  },
  {
    id: 20,
    slug: 'hipertrofia-calistenia',
    nombre: 'Hipertrofia con Calistenia',
    categoria: 'hibrido',
    nivel: 'intermedio',
    duracion: '12 semanas',
    objetivo: 'hipertrofia',
    descripcion: 'Construye músculo serio con tu propio peso. Técnicas avanzadas de sobrecarga progresiva.',
    precio: '$59',
    destacado: false,
    rating: 4.7,
    cantidadVideos: 50,
    beneficios: ['Hipertrofia sin pesas', 'Técnicas de intensidad avanzadas', 'Progresión al ángulo', 'Bandas de resistencia integradas'],
  },
  {
    id: 21,
    slug: 'strength-athlete',
    nombre: 'Strength Athlete',
    categoria: 'hibrido',
    nivel: 'avanzado',
    duracion: '20 semanas',
    objetivo: 'fuerza',
    descripcion: 'Rendimiento atlético completo. Para el atleta que quiere ser más fuerte en absolutamente todo.',
    precio: '$79',
    destacado: false,
    rating: 4.9,
    cantidadVideos: 70,
    beneficios: ['Rendimiento deportivo total', 'Fuerza en todos los planos', 'Potencia y velocidad', 'Periodización anual completa'],
  },
  {
    id: 22,
    slug: 'athletic-performance',
    nombre: 'Athletic Performance',
    categoria: 'hibrido',
    nivel: 'avanzado',
    duracion: '16 semanas',
    objetivo: 'habilidades',
    descripcion: 'Optimiza tu rendimiento atlético completo: velocidad, potencia, agilidad y resistencia de élite.',
    precio: '$69',
    destacado: false,
    rating: 4.8,
    cantidadVideos: 64,
    beneficios: ['Velocidad y agilidad de élite', 'Potencia explosiva', 'Resistencia de alto nivel', 'Recuperación activa integrada'],
  },
];
